import type { SoloDefinition } from "./solo-types.js";

// ─── Bundled Solo Definitions ───────────────────────────────────────────────
// Ported from OpenFang HAND.toml files, adapted for Paperclip.

export const BUNDLED_SOLOS: Record<string, SoloDefinition> = {
    // ═══════════════════════════════════════════════════════════════════════════
    // Browser Solo
    // ═══════════════════════════════════════════════════════════════════════════
    browser: {
        id: "browser",
        name: "Browser Solo",
        description:
            "Autonomous web browser — navigates sites, fills forms, clicks buttons, and completes multi-step web tasks with user approval for purchases",
        category: "productivity",
        icon: "🌐",
        tools: [
            "browser_navigate", "browser_click", "browser_type",
            "browser_screenshot", "browser_read_page", "browser_close",
            "web_search", "web_fetch",
            "memory_store", "memory_recall",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
            "schedule_create", "schedule_list", "schedule_delete",
            "file_write", "file_read",
        ],
        requires: [
            {
                key: "python3",
                label: "Python 3 must be installed",
                requirement_type: "binary",
                check_value: "python",
                description: "Python 3 is required to run Playwright, the browser automation library that powers this solo.",
                install: {
                    macos: "brew install python3",
                    windows: "winget install Python.Python.3.12",
                    linux_apt: "sudo apt install python3",
                    linux_dnf: "sudo dnf install python3",
                    linux_pacman: "sudo pacman -S python",
                    manual_url: "https://www.python.org/downloads/",
                    estimated_time: "2-5 min",
                },
            },
            {
                key: "playwright",
                label: "Playwright must be installed",
                requirement_type: "binary",
                check_value: "playwright",
                description: "Playwright is a browser automation framework. After installing via pip, you also need to install browser binaries.",
                install: {
                    macos: "pip3 install playwright && playwright install chromium",
                    windows: "pip install playwright && playwright install chromium",
                    linux_apt: "pip3 install playwright && playwright install chromium",
                    pip: "pip install playwright && playwright install chromium",
                    manual_url: "https://playwright.dev/python/docs/intro",
                    estimated_time: "3-5 min",
                    steps: [
                        "Install Playwright: pip install playwright",
                        "Install browser binaries: playwright install chromium",
                    ],
                },
            },
        ],
        settings: [
            {
                key: "headless",
                label: "Headless Mode",
                description: "Run the browser without a visible window (recommended for servers)",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "approval_mode",
                label: "Purchase Approval",
                description: "Require explicit user confirmation before completing any purchase or payment",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "max_pages_per_task",
                label: "Max Pages Per Task",
                description: "Maximum number of page navigations allowed per task to prevent runaway browsing",
                setting_type: "select",
                default: "20",
                options: [
                    { value: "10", label: "10 pages (conservative)" },
                    { value: "20", label: "20 pages (balanced)" },
                    { value: "50", label: "50 pages (thorough)" },
                ],
            },
            {
                key: "default_wait",
                label: "Default Wait After Action",
                description: "How long to wait after clicking or navigating for the page to settle",
                setting_type: "select",
                default: "auto",
                options: [
                    { value: "auto", label: "Auto-detect (wait for DOM)" },
                    { value: "1", label: "1 second" },
                    { value: "3", label: "3 seconds" },
                ],
            },
            {
                key: "screenshot_on_action",
                label: "Screenshot After Actions",
                description: "Automatically take a screenshot after every click/navigate for visual verification",
                setting_type: "toggle",
                default: "false",
            },
        ],
        agent: {
            name: "browser-solo",
            description: "AI web browser — navigates websites, fills forms, searches products, and completes multi-step web tasks autonomously with safety guardrails",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.3,
            max_iterations: 60,
            system_prompt: `You are Browser Solo — an autonomous web browser agent that interacts with real websites on behalf of the user. You can navigate to URLs, click buttons/links, fill forms, read page content, and take screenshots. Follow a multi-phase approach: understand the task, navigate & observe, interact, and report results. CRITICAL: Never auto-complete purchases without explicit user approval. Never store passwords or credit card numbers.`,
        },
        dashboard: {
            metrics: [
                { label: "Pages Visited", memory_key: "browser_solo_pages_visited", format: "number" },
                { label: "Tasks Completed", memory_key: "browser_solo_tasks_completed", format: "number" },
                { label: "Screenshots", memory_key: "browser_solo_screenshots_taken", format: "number" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Clip Solo
    // ═══════════════════════════════════════════════════════════════════════════
    clip: {
        id: "clip",
        name: "Clip Solo",
        description:
            "Turns long-form video into viral short clips with captions and thumbnails",
        category: "content",
        icon: "🎬",
        tools: ["shell_exec", "file_read", "file_write", "file_list", "web_fetch", "memory_store", "memory_recall"],
        requires: [
            {
                key: "ffmpeg",
                label: "FFmpeg must be installed",
                requirement_type: "binary",
                check_value: "ffmpeg",
                description: "FFmpeg is the core video processing engine used to extract clips, burn captions, crop to vertical, and generate thumbnails.",
                install: {
                    macos: "brew install ffmpeg",
                    windows: "winget install Gyan.FFmpeg",
                    linux_apt: "sudo apt install ffmpeg",
                    linux_dnf: "sudo dnf install ffmpeg-free",
                    linux_pacman: "sudo pacman -S ffmpeg",
                    manual_url: "https://ffmpeg.org/download.html",
                    estimated_time: "2-5 min",
                },
            },
            {
                key: "ffprobe",
                label: "FFprobe must be installed (ships with FFmpeg)",
                requirement_type: "binary",
                check_value: "ffprobe",
                description: "FFprobe analyzes video metadata (duration, resolution, codecs). It ships bundled with FFmpeg.",
                install: {
                    macos: "brew install ffmpeg",
                    windows: "winget install Gyan.FFmpeg",
                    linux_apt: "sudo apt install ffmpeg",
                    manual_url: "https://ffmpeg.org/download.html",
                    estimated_time: "Bundled with FFmpeg",
                },
            },
            {
                key: "yt-dlp",
                label: "yt-dlp must be installed",
                requirement_type: "binary",
                check_value: "yt-dlp",
                description: "yt-dlp downloads videos from YouTube, Vimeo, Twitter, and 1000+ other sites.",
                install: {
                    macos: "brew install yt-dlp",
                    windows: "winget install yt-dlp.yt-dlp",
                    linux_apt: "sudo apt install yt-dlp",
                    pip: "pip install yt-dlp",
                    manual_url: "https://github.com/yt-dlp/yt-dlp#installation",
                    estimated_time: "1-2 min",
                },
            },
        ],
        settings: [
            {
                key: "stt_provider",
                label: "Speech-to-Text Provider",
                description: "How audio is transcribed to text for captions and clip selection",
                setting_type: "select",
                default: "auto",
                options: [
                    { value: "auto", label: "Auto-detect (best available)" },
                    { value: "whisper_local", label: "Local Whisper", binary: "whisper" },
                    { value: "groq_whisper", label: "Groq Whisper API (fast, free tier)", provider_env: "GROQ_API_KEY" },
                    { value: "openai_whisper", label: "OpenAI Whisper API", provider_env: "OPENAI_API_KEY" },
                    { value: "deepgram", label: "Deepgram Nova-2", provider_env: "DEEPGRAM_API_KEY" },
                ],
            },
            {
                key: "tts_provider",
                label: "Text-to-Speech Provider",
                description: "Optional voice-over or narration generation for clips",
                setting_type: "select",
                default: "none",
                options: [
                    { value: "none", label: "Disabled (captions only)" },
                    { value: "edge_tts", label: "Edge TTS (free)", binary: "edge-tts" },
                    { value: "openai_tts", label: "OpenAI TTS", provider_env: "OPENAI_API_KEY" },
                    { value: "elevenlabs", label: "ElevenLabs", provider_env: "ELEVENLABS_API_KEY" },
                ],
            },
            {
                key: "elevenlabs_api_key",
                label: "ElevenLabs API Key",
                description: "API key from elevenlabs.io for high-quality text-to-speech. Required when ElevenLabs TTS is selected.",
                setting_type: "text",
                env_var: "ELEVENLABS_API_KEY",
                default: "",
            },
            {
                key: "publish_target",
                label: "Publish Clips To",
                description: "Where to send finished clips after processing. Leave as 'Local only' to skip publishing.",
                setting_type: "select",
                default: "local_only",
                options: [
                    { value: "local_only", label: "Local only (no publishing)" },
                    { value: "telegram", label: "Telegram channel" },
                    { value: "whatsapp", label: "WhatsApp contact/group" },
                    { value: "both", label: "Telegram + WhatsApp" },
                ],
            },
            {
                key: "telegram_bot_token",
                label: "Telegram Bot Token",
                description: "From @BotFather on Telegram. Bot must be admin in the target channel.",
                setting_type: "text",
                default: "",
            },
            {
                key: "telegram_chat_id",
                label: "Telegram Chat ID",
                description: "Channel: -100XXXXXXXXXX or @channelname.",
                setting_type: "text",
                default: "",
            },
            {
                key: "whatsapp_token",
                label: "WhatsApp Access Token",
                description: "Permanent token from Meta Business Settings > System Users.",
                setting_type: "text",
                default: "",
            },
            {
                key: "whatsapp_phone_id",
                label: "WhatsApp Phone Number ID",
                description: "From Meta Developer Portal > WhatsApp > API Setup.",
                setting_type: "text",
                default: "",
            },
            {
                key: "whatsapp_recipient",
                label: "WhatsApp Recipient",
                description: "Phone number in international format, no + or spaces (e.g. 14155551234).",
                setting_type: "text",
                default: "",
            },
        ],
        agent: {
            name: "clip-solo",
            description: "AI video editor — downloads, transcribes, and creates viral short clips from any video URL or file",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 8192,
            temperature: 0.4,
            max_iterations: 40,
            system_prompt: `You are Clip Solo — an AI-powered shorts factory that turns any video URL or file into viral short clips. Follow the pipeline: Intake → Download → Transcribe → Analyze → Extract → TTS (optional) → Publish (optional) → Report. Use shell_exec for all commands. Never fabricate output. Use file_write for creating SRT/text files.`,
        },
        dashboard: {
            metrics: [
                { label: "Jobs Completed", memory_key: "clip_solo_jobs_completed", format: "number" },
                { label: "Clips Generated", memory_key: "clip_solo_clips_generated", format: "number" },
                { label: "Total Duration", memory_key: "clip_solo_total_duration_secs", format: "duration" },
                { label: "Published to Telegram", memory_key: "clip_solo_clips_published_telegram", format: "number" },
                { label: "Published to WhatsApp", memory_key: "clip_solo_clips_published_whatsapp", format: "number" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Collector Solo
    // ═══════════════════════════════════════════════════════════════════════════
    collector: {
        id: "collector",
        name: "Collector Solo",
        description:
            "Autonomous intelligence collector — monitors any target continuously with change detection and knowledge graphs",
        category: "data",
        icon: "🔍",
        tools: [
            "shell_exec", "file_read", "file_write", "file_list",
            "web_fetch", "web_search", "memory_store", "memory_recall",
            "schedule_create", "schedule_list", "schedule_delete",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
            "event_publish",
        ],
        settings: [
            {
                key: "target_subject",
                label: "Target Subject",
                description: "What to monitor (company name, person, technology, market, topic)",
                setting_type: "text",
                default: "",
            },
            {
                key: "collection_depth",
                label: "Collection Depth",
                description: "How deep to dig on each cycle",
                setting_type: "select",
                default: "deep",
                options: [
                    { value: "surface", label: "Surface (headlines only)" },
                    { value: "deep", label: "Deep (full articles + sources)" },
                    { value: "exhaustive", label: "Exhaustive (multi-hop research)" },
                ],
            },
            {
                key: "update_frequency",
                label: "Update Frequency",
                description: "How often to run collection sweeps",
                setting_type: "select",
                default: "daily",
                options: [
                    { value: "hourly", label: "Every hour" },
                    { value: "every_6h", label: "Every 6 hours" },
                    { value: "daily", label: "Daily" },
                    { value: "weekly", label: "Weekly" },
                ],
            },
            {
                key: "focus_area",
                label: "Focus Area",
                description: "Lens through which to analyze collected intelligence",
                setting_type: "select",
                default: "general",
                options: [
                    { value: "market", label: "Market Intelligence" },
                    { value: "business", label: "Business Intelligence" },
                    { value: "competitor", label: "Competitor Analysis" },
                    { value: "person", label: "Person Tracking" },
                    { value: "technology", label: "Technology Monitoring" },
                    { value: "general", label: "General Intelligence" },
                ],
            },
            {
                key: "alert_on_changes",
                label: "Alert on Changes",
                description: "Publish an event when significant changes are detected",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "report_format",
                label: "Report Format",
                description: "Output format for intelligence reports",
                setting_type: "select",
                default: "markdown",
                options: [
                    { value: "markdown", label: "Markdown" },
                    { value: "json", label: "JSON" },
                    { value: "html", label: "HTML" },
                ],
            },
            {
                key: "max_sources_per_cycle",
                label: "Max Sources Per Cycle",
                description: "Maximum number of sources to process per collection sweep",
                setting_type: "select",
                default: "30",
                options: [
                    { value: "10", label: "10 sources" },
                    { value: "30", label: "30 sources" },
                    { value: "50", label: "50 sources" },
                    { value: "100", label: "100 sources" },
                ],
            },
            {
                key: "track_sentiment",
                label: "Track Sentiment",
                description: "Analyze and track sentiment trends over time",
                setting_type: "toggle",
                default: "false",
            },
        ],
        agent: {
            name: "collector-solo",
            description: "AI intelligence collector — monitors any target continuously with OSINT techniques, knowledge graphs, and change detection",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.3,
            max_iterations: 60,
            system_prompt: `You are Collector Solo — an autonomous intelligence collector that monitors any target 24/7, building a living knowledge graph and detecting changes over time. Follow the phases: Schedule & Init → Source Discovery → Collection Sweep → Knowledge Graph → Change Detection → Report → Persist State. Never fabricate intelligence.`,
        },
        dashboard: {
            metrics: [
                { label: "Data Points", memory_key: "collector_solo_data_points", format: "number" },
                { label: "Entities Tracked", memory_key: "collector_solo_entities_tracked", format: "number" },
                { label: "Reports Generated", memory_key: "collector_solo_reports_generated", format: "number" },
                { label: "Last Update", memory_key: "collector_solo_last_update", format: "text" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Lead Solo
    // ═══════════════════════════════════════════════════════════════════════════
    lead: {
        id: "lead",
        name: "Lead Solo",
        description:
            "Autonomous lead generation — discovers, enriches, and delivers qualified leads on a schedule",
        category: "data",
        icon: "📊",
        tools: [
            "shell_exec", "file_read", "file_write", "file_list",
            "web_fetch", "web_search", "memory_store", "memory_recall",
            "schedule_create", "schedule_list", "schedule_delete",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
        ],
        settings: [
            {
                key: "target_industry",
                label: "Target Industry",
                description: "Industry vertical to focus on (e.g. SaaS, fintech, healthcare, e-commerce)",
                setting_type: "text",
                default: "",
            },
            {
                key: "target_role",
                label: "Target Role",
                description: "Decision-maker titles to target (e.g. CTO, VP Engineering, Head of Product)",
                setting_type: "text",
                default: "",
            },
            {
                key: "company_size",
                label: "Company Size",
                description: "Filter leads by company size",
                setting_type: "select",
                default: "any",
                options: [
                    { value: "any", label: "Any size" },
                    { value: "startup", label: "Startup (1-50)" },
                    { value: "smb", label: "SMB (50-500)" },
                    { value: "enterprise", label: "Enterprise (500+)" },
                ],
            },
            {
                key: "lead_source",
                label: "Lead Source",
                description: "Primary method for discovering leads",
                setting_type: "select",
                default: "web_search",
                options: [
                    { value: "web_search", label: "Web Search" },
                    { value: "linkedin_public", label: "LinkedIn (public profiles)" },
                    { value: "crunchbase", label: "Crunchbase" },
                    { value: "custom", label: "Custom (specify in prompt)" },
                ],
            },
            {
                key: "output_format",
                label: "Output Format",
                description: "Report delivery format",
                setting_type: "select",
                default: "csv",
                options: [
                    { value: "csv", label: "CSV" },
                    { value: "json", label: "JSON" },
                    { value: "markdown_table", label: "Markdown Table" },
                ],
            },
            {
                key: "leads_per_report",
                label: "Leads Per Report",
                description: "Number of leads to include in each report",
                setting_type: "select",
                default: "25",
                options: [
                    { value: "10", label: "10 leads" },
                    { value: "25", label: "25 leads" },
                    { value: "50", label: "50 leads" },
                    { value: "100", label: "100 leads" },
                ],
            },
            {
                key: "delivery_schedule",
                label: "Delivery Schedule",
                description: "When to generate and deliver lead reports",
                setting_type: "select",
                default: "daily_9am",
                options: [
                    { value: "daily_7am", label: "Daily at 7 AM" },
                    { value: "daily_9am", label: "Daily at 9 AM" },
                    { value: "weekdays_8am", label: "Weekdays at 8 AM" },
                    { value: "weekly_monday", label: "Weekly on Monday" },
                ],
            },
            {
                key: "geo_focus",
                label: "Geographic Focus",
                description: "Geographic region to prioritize (e.g. US, Europe, APAC, global)",
                setting_type: "text",
                default: "",
            },
            {
                key: "enrichment_depth",
                label: "Enrichment Depth",
                description: "How much context to gather per lead",
                setting_type: "select",
                default: "standard",
                options: [
                    { value: "basic", label: "Basic (name, title, company)" },
                    { value: "standard", label: "Standard (+ company size, industry, tech stack)" },
                    { value: "deep", label: "Deep (+ funding, recent news, social profiles)" },
                ],
            },
        ],
        agent: {
            name: "lead-solo",
            description: "AI lead generation engine — discovers, enriches, deduplicates, and delivers qualified leads on your schedule",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.3,
            max_iterations: 50,
            system_prompt: `You are Lead Solo — an autonomous lead generation engine that discovers, enriches, and delivers qualified leads 24/7. Follow the phases: State Recovery → Target Profile → Lead Discovery → Enrichment → Deduplication & Scoring → Report → Persist State. Never fabricate lead data. Only use publicly available information.`,
        },
        dashboard: {
            metrics: [
                { label: "Leads Found", memory_key: "lead_solo_leads_found", format: "number" },
                { label: "Reports Generated", memory_key: "lead_solo_reports_generated", format: "number" },
                { label: "Last Report", memory_key: "lead_solo_last_report_date", format: "text" },
                { label: "Unique Companies", memory_key: "lead_solo_unique_companies", format: "number" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Predictor Solo
    // ═══════════════════════════════════════════════════════════════════════════
    predictor: {
        id: "predictor",
        name: "Predictor Solo",
        description:
            "Autonomous future predictor — collects signals, builds reasoning chains, makes calibrated predictions, and tracks accuracy",
        category: "data",
        icon: "🔮",
        tools: [
            "shell_exec", "file_read", "file_write", "file_list",
            "web_fetch", "web_search", "memory_store", "memory_recall",
            "schedule_create", "schedule_list", "schedule_delete",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
        ],
        settings: [
            {
                key: "prediction_domain",
                label: "Prediction Domain",
                description: "Primary domain for predictions",
                setting_type: "select",
                default: "tech",
                options: [
                    { value: "tech", label: "Technology" },
                    { value: "finance", label: "Finance & Markets" },
                    { value: "geopolitics", label: "Geopolitics" },
                    { value: "climate", label: "Climate & Energy" },
                    { value: "general", label: "General (cross-domain)" },
                ],
            },
            {
                key: "time_horizon",
                label: "Time Horizon",
                description: "How far ahead to predict",
                setting_type: "select",
                default: "3_months",
                options: [
                    { value: "1_week", label: "1 week" },
                    { value: "1_month", label: "1 month" },
                    { value: "3_months", label: "3 months" },
                    { value: "1_year", label: "1 year" },
                ],
            },
            {
                key: "data_sources",
                label: "Data Sources",
                description: "What types of sources to monitor for signals",
                setting_type: "select",
                default: "all",
                options: [
                    { value: "news", label: "News only" },
                    { value: "social", label: "Social media" },
                    { value: "financial", label: "Financial data" },
                    { value: "academic", label: "Academic papers" },
                    { value: "all", label: "All sources" },
                ],
            },
            {
                key: "report_frequency",
                label: "Report Frequency",
                description: "How often to generate prediction reports",
                setting_type: "select",
                default: "weekly",
                options: [
                    { value: "daily", label: "Daily" },
                    { value: "weekly", label: "Weekly" },
                    { value: "biweekly", label: "Biweekly" },
                    { value: "monthly", label: "Monthly" },
                ],
            },
            {
                key: "predictions_per_report",
                label: "Predictions Per Report",
                description: "Number of predictions to include per report",
                setting_type: "select",
                default: "5",
                options: [
                    { value: "3", label: "3 predictions" },
                    { value: "5", label: "5 predictions" },
                    { value: "10", label: "10 predictions" },
                    { value: "20", label: "20 predictions" },
                ],
            },
            {
                key: "track_accuracy",
                label: "Track Accuracy",
                description: "Score past predictions when their time horizon expires",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "confidence_threshold",
                label: "Confidence Threshold",
                description: "Minimum confidence to include a prediction",
                setting_type: "select",
                default: "medium",
                options: [
                    { value: "low", label: "Low (20%+ confidence)" },
                    { value: "medium", label: "Medium (40%+ confidence)" },
                    { value: "high", label: "High (70%+ confidence)" },
                ],
            },
            {
                key: "contrarian_mode",
                label: "Contrarian Mode",
                description: "Actively seek and present counter-consensus predictions",
                setting_type: "toggle",
                default: "false",
            },
        ],
        agent: {
            name: "predictor-solo",
            description: "AI forecasting engine — collects signals, builds reasoning chains, makes calibrated predictions, and tracks accuracy over time",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.5,
            max_iterations: 60,
            system_prompt: `You are Predictor Solo — an autonomous forecasting engine inspired by superforecasting principles. Collect signals, build reasoning chains, make calibrated predictions, and rigorously track accuracy. Always make predictions specific and falsifiable. Never express 0% or 100% confidence. Track ALL predictions — don't selectively forget bad ones.`,
        },
        dashboard: {
            metrics: [
                { label: "Predictions Made", memory_key: "predictor_solo_predictions_made", format: "number" },
                { label: "Accuracy", memory_key: "predictor_solo_accuracy_pct", format: "percentage" },
                { label: "Reports Generated", memory_key: "predictor_solo_reports_generated", format: "number" },
                { label: "Active Predictions", memory_key: "predictor_solo_active_predictions", format: "number" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Researcher Solo
    // ═══════════════════════════════════════════════════════════════════════════
    researcher: {
        id: "researcher",
        name: "Researcher Solo",
        description:
            "Autonomous deep researcher — exhaustive investigation, cross-referencing, fact-checking, and structured reports",
        category: "productivity",
        icon: "🧪",
        tools: [
            "shell_exec", "file_read", "file_write", "file_list",
            "web_fetch", "web_search", "memory_store", "memory_recall",
            "schedule_create", "schedule_list", "schedule_delete",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
            "event_publish",
        ],
        settings: [
            {
                key: "research_depth",
                label: "Research Depth",
                description: "How exhaustive each investigation should be",
                setting_type: "select",
                default: "thorough",
                options: [
                    { value: "quick", label: "Quick (5-10 sources, 1 pass)" },
                    { value: "thorough", label: "Thorough (20-30 sources, cross-referenced)" },
                    { value: "exhaustive", label: "Exhaustive (50+ sources, multi-pass, fact-checked)" },
                ],
            },
            {
                key: "output_style",
                label: "Output Style",
                description: "How to format research reports",
                setting_type: "select",
                default: "detailed",
                options: [
                    { value: "brief", label: "Brief (executive summary, 1-2 pages)" },
                    { value: "detailed", label: "Detailed (structured report, 5-10 pages)" },
                    { value: "academic", label: "Academic (formal paper style with citations)" },
                    { value: "executive", label: "Executive (key findings + recommendations)" },
                ],
            },
            {
                key: "source_verification",
                label: "Source Verification",
                description: "Cross-check claims across multiple sources before including",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "max_sources",
                label: "Max Sources",
                description: "Maximum number of sources to consult per investigation",
                setting_type: "select",
                default: "30",
                options: [
                    { value: "10", label: "10 sources" },
                    { value: "30", label: "30 sources" },
                    { value: "50", label: "50 sources" },
                    { value: "unlimited", label: "Unlimited" },
                ],
            },
            {
                key: "auto_follow_up",
                label: "Auto Follow-Up",
                description: "Automatically research follow-up questions discovered during investigation",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "save_research_log",
                label: "Save Research Log",
                description: "Save detailed search queries and source evaluation notes",
                setting_type: "toggle",
                default: "false",
            },
            {
                key: "citation_style",
                label: "Citation Style",
                description: "How to cite sources in reports",
                setting_type: "select",
                default: "inline_url",
                options: [
                    { value: "inline_url", label: "Inline URLs" },
                    { value: "footnotes", label: "Footnotes" },
                    { value: "academic_apa", label: "Academic (APA)" },
                    { value: "numbered", label: "Numbered references" },
                ],
            },
            {
                key: "language",
                label: "Language",
                description: "Primary language for research and output",
                setting_type: "select",
                default: "english",
                options: [
                    { value: "english", label: "English" },
                    { value: "spanish", label: "Spanish" },
                    { value: "french", label: "French" },
                    { value: "german", label: "German" },
                    { value: "chinese", label: "Chinese" },
                    { value: "japanese", label: "Japanese" },
                    { value: "auto", label: "Auto-detect" },
                ],
            },
        ],
        agent: {
            name: "researcher-solo",
            description: "AI deep researcher — conducts exhaustive investigations with cross-referencing, fact-checking, and structured reports",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.3,
            max_iterations: 80,
            system_prompt: `You are Researcher Solo — an autonomous deep research agent that conducts exhaustive investigations, cross-references sources, fact-checks claims, and produces comprehensive structured reports. Follow the phases: Question Analysis → Search Strategy → Information Gathering → Cross-Reference → Fact-Check → Report. NEVER fabricate sources or data.`,
        },
        dashboard: {
            metrics: [
                { label: "Queries Solved", memory_key: "researcher_solo_queries_solved", format: "number" },
                { label: "Sources Cited", memory_key: "researcher_solo_sources_cited", format: "number" },
                { label: "Reports Generated", memory_key: "researcher_solo_reports_generated", format: "number" },
                { label: "Active Investigations", memory_key: "researcher_solo_active_investigations", format: "number" },
            ],
        },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // Twitter Solo
    // ═══════════════════════════════════════════════════════════════════════════
    twitter: {
        id: "twitter",
        name: "Twitter Solo",
        description:
            "Autonomous Twitter/X manager — content creation, scheduled posting, engagement, and performance tracking",
        category: "communication",
        icon: "𝕏",
        tools: [
            "shell_exec", "file_read", "file_write", "file_list",
            "web_fetch", "web_search", "memory_store", "memory_recall",
            "schedule_create", "schedule_list", "schedule_delete",
            "knowledge_add_entity", "knowledge_add_relation", "knowledge_query",
            "event_publish",
        ],
        requires: [
            {
                key: "TWITTER_BEARER_TOKEN",
                label: "Twitter API Bearer Token",
                requirement_type: "api_key",
                check_value: "TWITTER_BEARER_TOKEN",
                description: "A Bearer Token from the Twitter/X Developer Portal. Required for reading and posting tweets via the Twitter API v2.",
                install: {
                    signup_url: "https://developer.twitter.com/en/portal/dashboard",
                    docs_url: "https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens",
                    env_example: "TWITTER_BEARER_TOKEN=AAAA...your_token_here",
                    estimated_time: "5-10 min",
                    steps: [
                        "Go to developer.twitter.com and sign in",
                        "Create a new Project and App",
                        "Navigate to 'Keys and tokens'",
                        "Generate a Bearer Token",
                        "Copy and set as environment variable",
                    ],
                },
            },
        ],
        settings: [
            {
                key: "twitter_bearer_token",
                label: "Twitter Bearer Token",
                description: "Bearer Token from the Twitter/X Developer Portal.",
                setting_type: "text",
                default: "",
            },
            {
                key: "twitter_style",
                label: "Content Style",
                description: "Voice and tone for your tweets",
                setting_type: "select",
                default: "professional",
                options: [
                    { value: "professional", label: "Professional" },
                    { value: "casual", label: "Casual" },
                    { value: "witty", label: "Witty" },
                    { value: "educational", label: "Educational" },
                    { value: "provocative", label: "Provocative" },
                    { value: "inspirational", label: "Inspirational" },
                ],
            },
            {
                key: "post_frequency",
                label: "Post Frequency",
                description: "How often to create and post content",
                setting_type: "select",
                default: "3_daily",
                options: [
                    { value: "1_daily", label: "1 per day" },
                    { value: "3_daily", label: "3 per day" },
                    { value: "5_daily", label: "5 per day" },
                    { value: "hourly", label: "Hourly" },
                ],
            },
            {
                key: "auto_reply",
                label: "Auto Reply",
                description: "Automatically reply to mentions and relevant conversations",
                setting_type: "toggle",
                default: "false",
            },
            {
                key: "auto_like",
                label: "Auto Like",
                description: "Automatically like tweets from your network and relevant content",
                setting_type: "toggle",
                default: "false",
            },
            {
                key: "content_topics",
                label: "Content Topics",
                description: "Topics to create content about (comma-separated, e.g. AI, startups, productivity)",
                setting_type: "text",
                default: "",
            },
            {
                key: "brand_voice",
                label: "Brand Voice",
                description: "Describe your unique voice (e.g. 'sarcastic founder who simplifies complex tech')",
                setting_type: "text",
                default: "",
            },
            {
                key: "thread_mode",
                label: "Thread Mode",
                description: "Include tweet threads (multi-tweet stories) in content mix",
                setting_type: "toggle",
                default: "true",
            },
            {
                key: "content_queue_size",
                label: "Content Queue Size",
                description: "Number of tweets to keep in the ready queue",
                setting_type: "select",
                default: "10",
                options: [
                    { value: "5", label: "5 tweets" },
                    { value: "10", label: "10 tweets" },
                    { value: "20", label: "20 tweets" },
                    { value: "50", label: "50 tweets" },
                ],
            },
            {
                key: "engagement_hours",
                label: "Engagement Hours",
                description: "When to check for mentions and engage",
                setting_type: "select",
                default: "business_hours",
                options: [
                    { value: "business_hours", label: "Business hours (9AM-6PM)" },
                    { value: "waking_hours", label: "Waking hours (7AM-11PM)" },
                    { value: "all_day", label: "All day (24/7)" },
                ],
            },
            {
                key: "approval_mode",
                label: "Approval Mode",
                description: "Write tweets to a queue file for your review instead of posting directly",
                setting_type: "toggle",
                default: "true",
            },
        ],
        agent: {
            name: "twitter-solo",
            description: "AI Twitter/X manager — creates content, manages posting schedule, handles engagement, and tracks performance",
            module: "builtin:chat",
            provider: "default",
            model: "default",
            max_tokens: 16384,
            temperature: 0.7,
            max_iterations: 50,
            system_prompt: `You are Twitter Solo — an autonomous Twitter/X content manager that creates, schedules, posts, and engages 24/7. Follow the phases: API Init → Schedule & Strategy → Content Research → Content Generation → Queue & Posting → Engagement → Performance Tracking → Persist State. Never post harmful content. In approval mode, always write to queue.`,
        },
        dashboard: {
            metrics: [
                { label: "Tweets Posted", memory_key: "twitter_solo_tweets_posted", format: "number" },
                { label: "Replies Sent", memory_key: "twitter_solo_replies_sent", format: "number" },
                { label: "Queue Size", memory_key: "twitter_solo_queue_size", format: "number" },
                { label: "Engagement Rate", memory_key: "twitter_solo_engagement_rate", format: "percentage" },
            ],
        },
    },
};

export function listSoloDefinitions(): SoloDefinition[] {
    return Object.values(BUNDLED_SOLOS);
}

export function getSoloDefinition(id: string): SoloDefinition | undefined {
    return BUNDLED_SOLOS[id];
}
